FROM node:18-alpine AS build

WORKDIR /app

ARG REACT_APP_API_URL
ARG NODE_OPTIONS=--openssl-legacy-provider

ENV REACT_APP_API_URL=$REACT_APP_API_URL
ENV NODE_OPTIONS=$NODE_OPTIONS

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
